### ISSUE TITLE
report1

### ISSUE THREAD

**Issue by blue-lwj** [blue-lwj/bugReport-#1]

**Comment by blue-lwj** [comment]
Build Identifier: 20110218-0911  java. lang.NullPointerException 	at org.aspectj.weaver.bcel.Utility.appendConversion(Utility.java:272) 	at org.aspectj.weaver.bcel.BcelVar.appendConvertableArrayLoad(BcelVar.java:81) 	at org.aspectj.weaver.bcel.BcelVar.createConvertableArrayLoad(BcelVar.java:101) 	at org.aspectj.weaver.bcel.BcelShadow.makeClosureClassAndReturnConstructor(BcelShadow.java:3066) 	at org.aspectj.weaver.bcel.BcelShadow.weaveAroundClosure(BcelShadow.java:2830) 	at org.aspectj.weaver.bcel.BcelAdvice.implementOn(BcelAdvice.java:342) 	at org.aspectj.weaver.Shadow.implementMungers(Shadow.java:630) 	at org.aspectj.weaver.Shadow.implement(Shadow.java:544) 	at org.aspectj.weaver.bcel.BcelClassWeaver.implement(BcelClassWeaver.java:3147) 	at org.aspectj.weaver.bcel.BcelClassWeaver.weave(BcelClassWeaver.java:490) 	at org.aspectj.weaver.bcel.BcelClassWeaver.weave(BcelClassWeaver.java:100) 	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1687) 	at org.aspectj.weaver.bcel.BcelWeaver.weaveWithoutDump(BcelWeaver.java:1631)
